apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlfmt
  name: sqlfmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqlfmt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sqlfmt
    spec:
      containers:
        - image: gcr.io/cockroach-dev-inf/cockroachlabs/sqlfmt:master
          imagePullPolicy: Always
          name: sqlfmt
          env:
          - name: SQLFMT_ADDR
            value: ":80"
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlfmt
  name: sqlfmt
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: sqlfmt
  type: NodePort
