apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sqlfmt
spec:
  serviceName: "sqlfmt"
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlfmt
    spec:
      containers:
      - name: sqlfmt
        image: gcr.io/hots-cockroach/sqlfmt:latest
        imagePullPolicy: Always
        env:
          - name: SQLFMT_ADDR
            value: ":443"
          - name: SQLFMT_AUTOCERT
            value: "sqlfmt.mattjibson.com,sqlfum.pt"
          - name: SQLFMT_CACHE
            value: "/datadir/cache"
          - name: SQLFMT_REDIR
            value: ":80"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: datadir
          mountPath: /datadir
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 0.1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sqlfmt
spec:
  selector:
    app: sqlfmt
  ports:
  - port: 443
    targetPort: 443
    name: https
  - port: 80
    targetPort: 80
    name: http
  - port: 7648
    targetPort: 80
    name: legacy
  type: LoadBalancer
  loadBalancerIP: "35.192.121.40"
