apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sqlfmt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlfmt
    spec:
      containers:
      - name: sqlfmt
        image: gcr.io/hots-cockroach/sqlfmt:latest
        imagePullPolicy: Always
        env:
          - name: ADDR
            value: ":80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sqlfmt
spec:
  selector:
    app: sqlfmt
  ports:
  - port: 7648
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "35.226.2.104"
